# -*- coding: utf-8 -*-

# -*- coding: utf-8 -*-

# inputs start

SELL_LOTS=1


INSTRUMENT_TYPE="NSE:NIFTY 50"
INSTRUMENT_NAME='NIFTY'
LOT_SIZE=50
STRIKE_SELL_DIFF=300

# INSTRUMENT_TYPE="NSE:NIFTY BANK"
# INSTRUMENT_NAME='BANKNIFTY'
# LOT_SIZE=25
# STRIKE_SELL_DIFF=500


# INSTRUMENT_TYPE="NSE:NIFTY FIN SERVICE"
# INSTRUMENT_NAME='FINNIFTY'
# LOT_SIZE=40
# STRIKE_SELL_DIFF=200

# inputs ends